#!/bin/bash
[ -z "$1" ] && echo "We can not start the script...Choose you log file
Example: /parser_apachelog apache_logs.txt" && exit 1

echo -n "1. From which ip were the most requests?
2. What is the most requested page?
3. How many requests were there from each ip?
4. What non-existent pages were clients referred to?
5. What time did site get the most requests?
6. What search bots have accessed the site? (UA + IP)" 
read answer
case $answer in
1) echo "You chose  1 answer"
awk '{print $1}' $1  | sort -nr | uniq -c | sort -nr | head -1
;;
2) echo "You chose  2 answer"
awk '{print $7}' $1 | sort | uniq -c | sort -nr | head -1
;;
3) echo "You chose  3 answer"
echo All requests $(awk '{print $1}' $1 | sort | uniq -c | sort -nr | wc -l)
awk '{print $1}' $1 | sort | uniq -c | sort -nr 
;;
4) echo "You chose  4 answer"
echo All requests $(grep " 404 " $1 | awk '{print $7,$11}' | sort | uniq -c | sort -nr | wc -l)
grep " 404 " $1 | awk '{print $7,$11}' | sort | uniq -c | sort -nr
;;
5) echo "You chose 5 answer"
#hours
awk -F: '{print $2":00"}' $1  | sort -n | uniq -c | sort -nr | head -1
# minute
#awk -F: '{print $2":"$3}' $1 | sort -n | uniq -c | sort -nr | head -1
;;
6) echo "You chose 6 answer"
grep bot $1 | awk -F'"' '{print $6,$1}' | cut --complement -d"-" -f2-3 | sort | uniq -c | sort -nr
#grep bot $1 | awk -F' - |\"' '{print $7, $1}' | sort | uniq -c | sort -nr
#grep bot $1 | awk '{ print $1 }' | sort | uniq -c | sort -rn | head -n 25 | \awk '{ printf("%5d\t%-15s\t", $1, $2); system("geoiplookup " $2 " | cut -d \\: -f2 ") }'
;;
*) echo "Bad chose"
esac